@host = http://localhost:3000

### Express API Healthcheck
GET {{host}}/health

> {%
    // Assert HTTP Status Code
    client.test("Status code is 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    // Assert JSON Response Payload
    client.test("Response success is true", function() {
        client.assert(response.body.success === true, "Success is not true");
    });

    client.test("Response status is 200", function() {
        client.assert(response.body.status === 200, "Status is not 200");
    });

    client.test("Response message is OK", function() {
        client.assert(response.body.message === 'OK', "Message is not OK");
    });

    client.test("Response data.uptime is a number", function() {
        client.assert(typeof response.body.data.uptime === 'number', "Uptime is missing or invalid");
    });

    client.test("Response timestamp is valid unix timestamp", function() {
        client.assert(Number.isInteger(response.body.timestamp), "Timestamp is not a valid unix timestamp");
    });

    client.test("Response timestamp is valid datetime value", function() {
        client.assert(!isNaN(Date.parse(new Date(response.body.timestamp * 1000))), "Timestamp is not a valid datetime value");
    });
%}